In [13]:
import numpy as np

In [14]:
#I/O Pairs

##### UPDATE: I added the 10 training pairs 
input_vector1 = np.array([.9, .87]).reshape(1,2)
target1 = 1

input_vector2 = np.array([1.31,.75]).reshape(1,2)
target2 = 1

input_vector3 = np.array([2.48,1.14]).reshape(1,2)
target3 = 0

input_vector4 = np.array([.41,1.87]).reshape(1,2)
target4 = 0

input_vector5 = np.array([2.45,.52]).reshape(1,2)
target5 = 0

input_vector6 = np.array([2.54,2.97]).reshape(1,2)
target6 = 1

input_vector7 = np.array([.07,.09]).reshape(1,2)
target7 = 1

input_vector8 = np.array([1.32,1.96]).reshape(1,2)
target8 = 0

input_vector9 = np.array([.94,.34]).reshape(1,2)
target9 = 1

input_vector10 = np.array([1.75,2.21]).reshape(1,2)
target10 = 0

##### UPDATE: I initialized all the weights as "1".
weight_layer_1 = np.array([[1, 1], [1, 1]])
weight_layer_2 = np.array([1, 1]).reshape(2,1)

eta = 1

bias = 0

In [15]:
class Layer:
    #initialize layer class
    def __init__(self, layer_weight, eta = 0,  bias = None):
        self.layer_weight = layer_weight
        self.layer_bias = bias
        self.eta = eta
    
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def get_layer_output_vector(self, inputs):
        self.activity = np.dot(inputs ,self.layer_weight)+self.layer_bias
        self.output_vector = 1/(1+np.exp(-self.activity))
        return self.output_vector

##### UPDATE: I created this to apply our threshold.
##### It is initialized so that an output of .5 or higher returns a "1".
##### The code only applies this threshold logic to the activation function output from the final node.
    def apply_threshold(self,output):
        self.final_output = 0
        if output >= .5:
            self.final_output = 1
        return self.final_output

##### UPDATE: Had to update this to calculate error based on the "final output",
##### aka the output after we apply our new threshold logic.
    def get_error_vector(self, desired_output):
        self.littleE_vector = desired_output - self.final_output
        return self.littleE_vector

##### UPDATE: Also updated to calculate delta based on the "final output".
##### I did not update the calc_delta_j below since I figured it should remain as is
##### (looking at the output_vector).
    def calc_delta_k(self, target):
        self.littleE = target - self.final_output
        self.bigE = 0.5*self.littleE**2
        self.delta_k = self.littleE*(1-self.final_output)*self.final_output
        return self.delta_k

    def calc_delta_j(self, delta_k, next_layer_weights):
        self.delta_j = (1-self.output_vector)*self.output_vector*(delta_k*next_layer_weights).T
        return self.delta_j
    
    def calc_delta_weights (self, delta, prev_layer_input):
        self.delta_weights = self.layer_weight + self.eta*delta*prev_layer_input.T
        self.delta_bias = self.layer_bias + self.eta*delta
        return self.delta_weights, self.delta_bias
    
    def update_layer_weights(self):
        self.layer_weight = self.delta_weights
        self.layer_bias = self.delta_bias

In [16]:
Layer1=Layer(weight_layer_1, eta, bias)
Layer2=Layer(weight_layer_2, eta, bias)

In [17]:
##### UPDATE: Does 30 iterations vice 15.  Loops through all 10 training I/Os.
##### Also included a step to apply the threshold logic.
for i in range(0,30):
    
    #I/O pair 1
    Layer1.get_layer_output_vector(input_vector1)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 1, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target1)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector1)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 2
    Layer1.get_layer_output_vector(input_vector2)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 2, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target2)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector2)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 3
    Layer1.get_layer_output_vector(input_vector3)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 3, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target3)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector3)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 4
    Layer1.get_layer_output_vector(input_vector4)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 4, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target4)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector4)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 5
    Layer1.get_layer_output_vector(input_vector5)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 5, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target5)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector5)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 6
    Layer1.get_layer_output_vector(input_vector6)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 6, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target6)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector6)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 7
    Layer1.get_layer_output_vector(input_vector7)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 7, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target7)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector7)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 8
    Layer1.get_layer_output_vector(input_vector8)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 8, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target8)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector8)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 9
    Layer1.get_layer_output_vector(input_vector9)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 9, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target9)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector9)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #I/O pair 10
    Layer1.get_layer_output_vector(input_vector10)
    Layer2.get_layer_output_vector(Layer1.output_vector)
    #print("Input 10, Iteration: ", i, " Layer output ", Layer2.output_vector)
    Layer2.apply_threshold(Layer2.output_vector)
    Layer2.calc_delta_k(target10)
    Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
    Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
    Layer1.calc_delta_weights(Layer1.delta_j, input_vector10)
    Layer1.update_layer_weights()
    Layer2.update_layer_weights()
    
    #print("---------")

In [18]:
Layer1.get_layer_output_vector(input_vector1)
Layer2.get_layer_output_vector(Layer1.output_vector)

array([[0.84669555]])

In [19]:
Layer2.calc_delta_k(target1)
Layer2.bigE

0.0

In [20]:
Layer1.get_layer_output_vector(input_vector2)
Layer2.get_layer_output_vector(Layer1.output_vector)

array([[0.85494304]])

In [21]:
Layer2.calc_delta_k(target2)
Layer2.bigE

0.0

In [22]:
##### Ignore this section... It's my working space to test stuff

Layer1.get_layer_output_vector(input_vector1)
print(Layer1.output_vector)
Layer2.get_layer_output_vector(Layer1.output_vector)
print(Layer2.output_vector)
Layer2.apply_threshold(Layer2.output_vector)
print(Layer2.final_output)
Layer2.calc_delta_k(target1)
print(Layer2.delta_k)
Layer2.calc_delta_weights(Layer2.delta_k, Layer1.output_vector)
print(Layer2.delta_weights)
Layer1.calc_delta_j(Layer2.delta_k, Layer2.layer_weight)
print(Layer1.delta_j)
Layer1.calc_delta_weights(Layer1.delta_j, input_vector1)
print(Layer1.delta_weights)

[[0.85445767 0.85445767]]
[[0.84669555]]
1
0
[[1.]
 [1.]]
[[0. 0.]]
[[1. 1.]
 [1. 1.]]
